### ISSUE TITLE
test_json throwing errors

### ISSUE THREAD

**Issue by j616** [bbc/nmos-common#27]
Seen when running `make test`
```
ERROR: test_dump_nmos_json (test_json.TestJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jamessa/BBC/IPStudio/dev/nmos-common/tests/test_json.py", line 89, in test_dump_nmos_json
    decoded = nmos_json.loads(fp.getvalue())
  File "nmoscommon/json.py", line 73, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "nmoscommon/json.py", line 96, in raw_decode
    value = self._reinterpret_object(value)
  File "nmoscommon/json.py", line 105, in _reinterpret_object
    o[key] = self._reinterpret_object(o[key])
  File "nmoscommon/json.py", line 113, in _reinterpret_object
    return Timestamp.from_tai_sec_nsec(o)
  File "nmoscommon/timestamp.py", line 498, in from_tai_sec_nsec
    return cls.from_sec_nsec(ts_str)
  File "nmoscommon/timestamp.py", line 171, in from_sec_nsec
    return cls(sec=sec, ns=ns, sign=sign)
  File "nmoscommon/timestamp.py", line 478, in __init__
    super(Timestamp, self).__init__(sec, ns, sign)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_dumps_nmos_json (test_json.TestJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jamessa/BBC/IPStudio/dev/nmos-common/tests/test_json.py", line 94, in test_dumps_nmos_json
    decoded = nmos_json.loads(encoded)
  File "nmoscommon/json.py", line 73, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "nmoscommon/json.py", line 96, in raw_decode
    value = self._reinterpret_object(value)
  File "nmoscommon/json.py", line 105, in _reinterpret_object
    o[key] = self._reinterpret_object(o[key])
  File "nmoscommon/json.py", line 113, in _reinterpret_object
    return Timestamp.from_tai_sec_nsec(o)
  File "nmoscommon/timestamp.py", line 498, in from_tai_sec_nsec
    return cls.from_sec_nsec(ts_str)
  File "nmoscommon/timestamp.py", line 171, in from_sec_nsec
    return cls(sec=sec, ns=ns, sign=sign)
  File "nmoscommon/timestamp.py", line 478, in __init__
    super(Timestamp, self).__init__(sec, ns, sign)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_load_nmos_json (test_json.TestJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jamessa/BBC/IPStudio/dev/nmos-common/tests/test_json.py", line 101, in test_load_nmos_json
    decoded = nmos_json.load(fp)
  File "nmoscommon/json.py", line 65, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "nmoscommon/json.py", line 96, in raw_decode
    value = self._reinterpret_object(value)
  File "nmoscommon/json.py", line 105, in _reinterpret_object
    o[key] = self._reinterpret_object(o[key])
  File "nmoscommon/json.py", line 113, in _reinterpret_object
    return Timestamp.from_tai_sec_nsec(o)
  File "nmoscommon/timestamp.py", line 498, in from_tai_sec_nsec
    return cls.from_sec_nsec(ts_str)
  File "nmoscommon/timestamp.py", line 171, in from_sec_nsec
    return cls(sec=sec, ns=ns, sign=sign)
  File "nmoscommon/timestamp.py", line 478, in __init__
    super(Timestamp, self).__init__(sec, ns, sign)
TypeError: super(type, obj): obj must be an instance or subtype of type

======================================================================
ERROR: test_loads_nmos_json (test_json.TestJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jamessa/BBC/IPStudio/dev/nmos-common/tests/test_json.py", line 106, in test_loads_nmos_json
    decoded = nmos_json.loads(NMOS_JSON_STRING)
  File "nmoscommon/json.py", line 73, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "nmoscommon/json.py", line 96, in raw_decode
    value = self._reinterpret_object(value)
  File "nmoscommon/json.py", line 105, in _reinterpret_object
    o[key] = self._reinterpret_object(o[key])
  File "nmoscommon/json.py", line 113, in _reinterpret_object
    return Timestamp.from_tai_sec_nsec(o)
  File "nmoscommon/timestamp.py", line 498, in from_tai_sec_nsec
    return cls.from_sec_nsec(ts_str)
  File "nmoscommon/timestamp.py", line 171, in from_sec_nsec
    return cls(sec=sec, ns=ns, sign=sign)
  File "nmoscommon/timestamp.py", line 478, in __init__
    super(Timestamp, self).__init__(sec, ns, sign)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by j616** [comment]
Fixed by https://github.com/bbc/nmos-common/pull/29/commits/c2bca19aa2f0f4e5a090384e140c4a56e79d227f
